### ISSUE TITLE
re:invent notebook html version

### ISSUE THREAD

**Issue by pelinbalci** [aws-samples/amazon-neptune-generative-ai-samples#12]
Hello, I've joined the session at re: invent. Thank you very much for sharing the notebook. Could you please add the HTML version of the notebook of "presentations/Data-models-for-Amazon-Neptune-using-gen-AI-and-diagram-as-code-tools/Data models for Amazon Neptune using gen AI and diagram-as-code tools.ipynb". Some of the graphs can't be seen. Thanks!

**Comment by kwokmeli** [comment]
[Data models for Amazon Neptune using gen AI and diagram-as-code tools - Jupyter Notebook.pdf](https://github.com/user-attachments/files/18169139/Data.models.for.Amazon.Neptune.using.gen.AI.and.diagram-as-code.tools.-.Jupyter.Notebook.pdf)
Hi, here is the PDF version attached. The HTML version doesn't fully render the graph visualizations generated by the openCypher queries so I had to export as PDF instead.

**Comment by pelinbalci** [comment]
Thank you! I've been looking for this. It was a great session. I can't wait to try it. Best,
